config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  root 'top#index'

  resources :studios, only: [:show] do
    resources :reserves, only: [:show, :update] do
      collection do
        get :duplicate
      end
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resources :chatrooms, only: [:index] do
      collection do
        get :room_judge
      end
    end
    
    collection do
      get :reserve
      get :notice
      get :search
    end
  end

  resources :user_reserves, only: [:index, :destroy]

  resources :posts do
    collection do
      get :search
    end
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :sessions, as: :music_sessions do
    resources :entry_sessions, only: [:create, :destroy]

    resources :entry_musics, only: [:create, :show, :edit, :update, :destroy] do
      resources :entry_parts, only: [:update] do
        member do
          get 'cancel'
        end
      end
    end

    collection do
      post :confirm
      get  :search
    end
  end
  get '*anything', to: 'errors#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]
  mount_uploader :img, ImageUploader

  has_many :user_reserves
  has_many :posts
  has_many :entry_rooms
  has_many :chatrooms, through: :entry_rooms
  has_many :entry_sessions
  has_many :sessions
  has_many :only_entry_sessions, through: :entry_sessions, source: :session
  has_many :entry_parts
  has_many :notices

  validates :nickname, presence: true
  validates :nickname, length: { maximum: 20, message: "は20文字以下で入力してください" }, allow_blank: true
  validates :last_name, presence: true
  validates :last_name, length: { maximum: 20, message: "は20文字以下で入力してください" }, allow_blank: true
  validates :first_name, presence: true
  validates :first_name, length: { maximum: 20, message: "は20文字以下で入力してください" }, allow_blank: true
  validates :tel_no, format: {with:/\A\d{9,11}\z/}, allow_blank: true
  
  def entry_part_praph
    praph_data = []
    praph_data << self.entry_parts.where(part_no: 1).count
    praph_data << self.entry_parts.where(part_no: 2).count
    praph_data << self.entry_parts.where(part_no: [3, 4]).count
    praph_data << self.entry_parts.where(part_no: 5).count
    praph_data << self.entry_parts.where(part_no: 6).count
    praph_data << self.entry_parts.where(part_no: 7).count
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    user = User.find_by(email: auth.info.email)
    # 会員登録済
    if user.present?
      sns = SnsCredential.create(
        user_id:  user.id,
        provider: auth.provider,
        uid:      uid,
        token:    auth.credentials.token
      )
    # 会員登録未
    else
      user = set_user(auth)
      sns = SnsCredential.create(
        user_id:  user.id,
        provider: auth.provider,
        uid:      uid,
        token:    auth.credentials.token
      )
    end
    # hashでsnsのidを設定
    return { user: user , sns_id: sns.id }
  end

  def self.set_user(auth)
    User.create(
      last_name:  auth.info.last_name,
      first_name: auth.info.first_name,
      nickname:   auth.info.name,
      email:      auth.info.email,
      img:        auth.info.image,
      password:   Devise.friendly_token[0,20]
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # callback for google
    def google_oauth2
      callback_for(:google)
    end
  
    def callback_for(provider)
      info = User.find_oauth(request.env["omniauth.auth"]) #usersモデルのメソッド
      @user = info[:user]
      sns_id = info[:sns_id]
      if @user.persisted? #userが存在したら
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      else #userが存在しなかったら
        redirect_to root_path
      end
    end
        
    def failure
      redirect_to root_path and return
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :notice]

  def show
    @user = User.find(params[:id])
    # スタジオ予約状況の取得
    if @user.id == current_user&.id
      @user_reserves = @user.user_reserves.where('reserve_date >= ?', Date.today).order('reserve_date').order('start_hour').limit(5)
    end
    # 参加セッション一覧の取得(主催のセッションは除く)
    @sessions = @user.only_entry_sessions.where.not(user_id: current_user.id)
    # 主催セッション一覧の取得
    @organizer_sessions = @user.sessions
    # 投稿一覧の取得
    @posts = @user.posts
    # エントリー数のグラフデータを取得
    gon.data = @user.entry_part_praph
  end

  def edit
    
  end

  def update
    begin
      @user.update!(user_params)
      redirect_to user_path(current_user.id)
    rescue ActiveRecord::RecordInvalid => e
      render :edit
    rescue => e
      error_log = ErrorLog.new
      error_log.create_log(params, e, request.remote_ip)
      render template: "common/error1"
    end
  end

  def notice
    @notices = current_user.notices.order("created_at DESC")
    @notices.each do |notice|
      notice.before_read_flg = notice.read_flg
    end
    update_notices = current_user.notices.where(read_flg: 0)
    update_notices.update(read_flg: 1)
  end

  def search
    @users = User.where("nickname LIKE ?", "%#{params[:search_name]}%").order("nickname")
    respond_to do |format|
      format.html
      format.json
    end
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :first_name, :last_name, :tel_no, :email, :profile, :img)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_notice_list.html.haml
- notices.each do |notice|
  .users-notice-list
    - if notice.before_read_flg == 0
      .users-notice-list__new-mark
        新着
    .users-notice-list__title
      = notice.title
    .users-notice-list__contents
      = notice.contents
    .users-notice-list__datetime
      通知日時：
      = notice.created_at.strftime("%Y/%m/%d %H:%M")
    

app/views/users/_side_menu.html.haml
.user-side-menu
  - if user_signed_in?
    - if current_user.id == @user.id
      .user-side-menu__links__link
        = link_to "マイページトップ", user_path(current_user)
      .user-side-menu__links__link
        = link_to "ユーザ情報編集", edit_user_path(current_user)
      .user-side-menu__links__link
        = link_to "メッセージ一覧", user_chatrooms_path(current_user)
      .user-side-menu__links__link
        = link_to "お知らせ", notice_users_path
    - else
      .user-side-menu__links__link
        = link_to "メッセージを送る", room_judge_user_chatrooms_path(@user)

app/views/users/edit.html.haml
.main-container
  .inner-container-wide
    .user-edit
      = form_with(model: @user, data: { remote: false }) do |f|
        .user-edit__title.main-title
          ユーザ情報編集
        %table.user-edit__form
          %tr
            %th
              プロフィール画像
            %td.profile-img
              - if @user.img.present?
                = image_tag(@user.img.url, class: "user-img-default")
              - else
                = image_tag("default_user.png", class: "user-img-default")
              = f.label :img, for: "set-image" do
                = f.file_field :img, id: "set-image", class: "set-image"
                .img-change-btn
                  変更する
          %tr
            %th
              アカウント名
            %td
              = f.text_field :nickname, value: @user.nickname, placeholder: '20字以内', class: "text-field-default"
          %tr
            %th
              プロフィール
            %td
              = f.text_area :profile, value: @user.profile, placeholder: '1000字以内', class: "text-area-default"
          %tr
            %th
              氏名
            %td
              = f.text_field :last_name, value: @user.last_name, placeholder: '性', class: "text-field-short"
              = f.text_field :first_name, value: @user.first_name, placeholder: '名', class: "text-field-short"
          %tr
            %th
              電話番号
            %td
              = f.text_field :tel_no, value: @user.tel_no, class: "text-field-short"
          %tr
            %th
              Email
            %td
              = f.text_field :email, value: @user.email, class: "text-field-short"
        .user-edit__button
          = f.submit "変更する", class: "edit-btn-default"
    .side-bar
      = render partial: "users/side_menu"

app/views/users/notice.html.haml
.main-container
  .inner-container-wide
    .users-notice
      .users-notice__title.main-title
        お知らせ
      .users-notice__info
        .users-notice__info__lists
          = render partial: "notice_list", locals: { notices: @notices }
    .side-bar
      = render partial: "users/side_menu"

app/views/users/reserve.html.haml
.user-reserve-page
  .main-container
    .inner-container
      .user-reserve
        .user-reserve__title.main-title
          スタジオ予約状況
        %table.user-reserve__info
          %tr.user-reserve__info__head
            %th.user-reserve__info__head__date
              日時
            %th.user-reserve__info__head__studio
              スタジオ
            %th.user-reserve__info__head__fee
              料金
            %th
              予約取消
          - @user_reserves.each do |user_reserve|
            %tr
              %td
                = user_reserve.reserve_date.strftime("%m月%d日")
                = user_reserve.start_hour.to_s + "時 〜"
                = user_reserve.end_hour.to_s + "時"
              %td
                = user_reserve.studio.name + " st"
              %td
                = user_reserve.payment_fee.to_s + " 円"
              %td
                - if Date.today < user_reserve.reserve_date
                  .user-reserve__info__link
                    = link_to "取消", "#", method: :post, class: "cancel-button"

app/views/users/show.html.haml
.main-container
  .inner-container-wide
    .mypage
      .mypage__profile
        .mypage__profile__title.main-title
          プロフィール
        .mypage__profile__top
          .mypage__profile__top__left
            - if @user.img.present?
              = image_tag(@user.img.url, class: "mypage__profile__top__left__image")
            - else
              = image_tag("default_user.png", class: "mypage__profile__top__left__image")
            .mypage__profile__top__left__name
              = @user.nickname
          .mypage__profile__top__right
            .mypage__profile__top__right__entry-part-cnt
              = @user.entry_parts.count
            %canvas(id="myChart" width="500" height="250")
            %script
              draw_graph();
        .mypage__profile__self-introduction
          = simple_format(@user.profile)
      .mypage__tabs
        %ul.mypage__tabs__header
          %li.mypage__tabs__header__tab.active
            %a 参加セッション
          %li.mypage__tabs__header__tab
            %a 投稿した記事
          - if current_user&.id == @user.id
            %li.mypage__tabs__header__tab
              %a スタジオ予約
        %ul.mypage__tabs__contents.active-contents
          .mypage-entry-sessions
            主催したセッション
          = render partial: "sessions/sessions", locals: { sessions: @organizer_sessions }
          .mypage-entry-sessions
            参加したセッション
          = render partial: "sessions/sessions", locals: { sessions: @sessions }
        %ul.mypage__tabs__contents
          = render partial: "posts/post", locals: { posts: @posts }
        - if current_user&.id == @user.id
          %ul.mypage__tabs__contents
            = render partial: "user_reserves/user_reserves", locals: { user_reserves: @user_reserves }
            .mypage__tabs__contents__note
              ※本日以降の予約を最大5件表示しています
            = link_to  user_reserves_path, class: "more-reserves-link" do
              すべての予約を見る
              = icon 'fas', 'angle-right'
    .side-bar
      = render partial: "side_menu"
= render partial: "user_reserves/cancel_modal"