config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  root 'top#index'

  resources :studios, only: [:show] do
    resources :reserves, only: [:show, :update] do
      collection do
        get :duplicate
      end
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resources :chatrooms, only: [:index] do
      collection do
        get :room_judge
      end
    end
    
    collection do
      get :reserve
      get :notice
      get :search
    end
  end

  resources :user_reserves, only: [:index, :destroy]

  resources :posts do
    collection do
      get :search
    end
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :sessions, as: :music_sessions do
    resources :entry_sessions, only: [:create, :destroy]

    resources :entry_musics, only: [:create, :show, :edit, :update, :destroy] do
      resources :entry_parts, only: [:update] do
        member do
          get 'cancel'
        end
      end
    end

    collection do
      post :confirm
      get  :search
    end
  end
  get '*anything', to: 'errors#routing_error'
end

app/views/shared/_flash.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/shared/_footer.html.haml
%footer.footer
  .footer__bottom
    .footer__bottom__copy-write
      &copy 2020 STUDIO Hummingbird reserved App.
    .footer__bottom__sns-links
      = link_to "https://github.com/yuya-yamaguchi/studio_reserve_app", target: ["_blank"] do
        = icon 'fab', 'github-square'
      

app/views/shared/_header.html.haml
%header.header
  .header__title.main-title
    = link_to "STUDIO Hummingbird", root_path
  .menues-bar-icon
    = icon 'fas', 'bars'
  %ul.header-menus
    %li.header-menus__menu
      = link_to "スタジオ", root_path
      %ul.sub-menus
        - @studio_lists.each do |studio_list|
          %li.sub-menus__menu
            = link_to studio_list.name, studio_path(studio_list.id)
    %li.header-menus__menu
      = link_to "掲示板", posts_path
      %ul.sub-menus
        %li.sub-menus__menu
          = link_to "投稿一覧", posts_path
        %li.sub-menus__menu
          = link_to "投稿する", new_post_path
    %li.header-menus__menu
      = link_to "セッション", music_sessions_path
      %ul.sub-menus
        %li.sub-menus__menu
          = link_to "セッション一覧", music_sessions_path
        %li.sub-menus__menu
          = link_to "セッションを開く", new_music_session_path
    - if user_signed_in?
      %li.header-menus__menu.unread-mark
        = link_to "マイページ", user_path(current_user)
        - if @unread_message_cnt + @unread_notice_cnt > 0
          .unread-mark__cnt
            = @unread_message_cnt + @unread_notice_cnt
        %ul.sub-menus
          %li.sub-menus__menu
            = link_to "スタジオ予約状況", user_reserves_path
          %li.sub-menus__menu.unread-mark
            = link_to "メッセージ", user_chatrooms_path(current_user)
            - if @unread_message_cnt > 0
              .unread-mark__cnt
                = @unread_message_cnt
          %li.sub-menus__menu.unread-mark
            = link_to "お知らせ", notice_users_path
            - if @unread_notice_cnt > 0
              .unread-mark__cnt
                = @unread_notice_cnt
          %li.sub-menus__menu
            = link_to "ログアウト", destroy_user_session_path, method: :delete
      - if current_user.admin_flg == true
        %li.header-menus__menu
          = link_to "管理者用", admin_root_path
    - else
      %li.header-menus__menu
        = link_to "新規会員登録", new_user_registration_path
      %li.header-menus__menu
        = link_to "ログイン", new_user_session_path

.sumaho-header
  %ul.s-header-menus
    %li.s-header-menus__menu
      スタジオ
      %ul.s-sub-menus
        - @studio_lists.each do |studio_list|
          %li.s-sub-menus__menu
            = link_to studio_list.name, studio_path(studio_list.id)
    %li.s-header-menus__menu
      掲示板
      %ul.s-sub-menus
        %li.s-sub-menus__menu
          = link_to "投稿一覧", posts_path
        %li.s-sub-menus__menu
          = link_to "投稿する", new_post_path
    %li.s-header-menus__menu
      セッション
      %ul.s-sub-menus
        %li.s-sub-menus__menu
          = link_to "セッション一覧", music_sessions_path
        %li.s-sub-menus__menu
          = link_to "セッションを開く", new_music_session_path
    - if user_signed_in?
      %li.s-header-menus__menu.unread-mark
        マイページ
        - if @unread_message_cnt + @unread_notice_cnt > 0
          .s-unread-mark__cnt
            = @unread_message_cnt + @unread_notice_cnt
        %ul.s-sub-menus
          %li.s-sub-menus__menu
            = link_to "スタジオ予約状況", user_reserves_path
          %li.s-sub-menus__menu.unread-mark
            = link_to "メッセージ", user_chatrooms_path(current_user)
            - if @unread_message_cnt > 0
              .s-unread-mark__cnt
                = @unread_message_cnt
          %li.s-sub-menus__menu.unread-mark
            = link_to "お知らせ", notice_users_path
            - if @unread_notice_cnt > 0
              .s-unread-mark__cnt
                = @unread_notice_cnt
          %li.s-sub-menus__menu
            = link_to "ログアウト", destroy_user_session_path, method: :delete
      - if current_user.admin_flg == true
        %li.s-header-menus__menu
          = link_to "管理者用", admin_root_path
    - else
      %li.s-header-menus__menu
        = link_to "新規会員登録", new_user_registration_path
      %li.s-header-menus__menu
        = link_to "ログイン", new_user_session_path