config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  root 'top#index'

  resources :studios, only: [:show] do
    resources :reserves, only: [:show, :update] do
      collection do
        get :duplicate
      end
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resources :chatrooms, only: [:index] do
      collection do
        get :room_judge
      end
    end
    
    collection do
      get :reserve
      get :notice
      get :search
    end
  end

  resources :user_reserves, only: [:index, :destroy]

  resources :posts do
    collection do
      get :search
    end
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :sessions, as: :music_sessions do
    resources :entry_sessions, only: [:create, :destroy]

    resources :entry_musics, only: [:create, :show, :edit, :update, :destroy] do
      resources :entry_parts, only: [:update] do
        member do
          get 'cancel'
        end
      end
    end

    collection do
      post :confirm
      get  :search
    end
  end
  get '*anything', to: 'errors#routing_error'
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :contents, presence: true

  enum post_type: {
    "---":              0,
    "バンドメンバー募集":  1,
    "バンド参加希望":      2,
    "その他":            99
  }, _prefix: true

  def self.search(search_params)
    post_type_num = post_type_string2num(search_params[:post_type])
    results = Post.all
    results = results.where('post_type = ?', post_type_num) if post_type_num != 0
    results = results.where('title LIKE(?)', "%#{search_params[:keyword]}%")
    results = results.order('created_at DESC')
    results
  end

  private
  def self.post_type_string2num(post_type_string)
    case post_type_string
    when "バンドメンバー募集"
      return 1
    when "バンド参加希望"
      return 2
    when "その他"
      return 99
    else
      return 0
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :sign_in_check, only: [:new, :edit, :create, :update]

  def index
    @posts = Post.all.order("updated_at DESC")
  end

  def new
    @post = Post.new
  end

  def show
    
  end

  def edit
    
  end

  def create
    begin
      @post = Post.new(post_params)
      @post.save!
      flash[:notice] = '投稿が完了しました'
      redirect_to post_path(@post)
    rescue ActiveRecord::RecordInvalid => e
      render action: :new
    rescue => e
      error_log = ErrorLog.new
      error_log.create_log(params, e, request.remote_ip)
      render template: "common/error1"
    end
  end

  def update
    begin
      @post.update!(post_params)
      flash[:notice] = '編集が完了しました'
      redirect_to post_path(@post)
    rescue ActiveRecord::RecordInvalid => e
      render :edit
    rescue => e
      error_log = ErrorLog.new
      error_log.create_log(params, e, request.remote_ip)
      render template: "common/error1"
    end
  end

  def destroy
    @post.destroy!
    flash[:notice] = '投稿を削除しました'
    redirect_to user_path(current_user)
  end

  def search
    @posts = Post.search(search_params)
    render template: 'posts/index'
  end

  private
  def post_params
    params.require(:post).permit(:title, :contents, :post_type).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def search_params
    params.permit(:post_type, :keyword)
  end

  def sign_in_check
    unless user_signed_in?
      flash[:notice] = 'ログイン（または会員登録）を行ってください'
      redirect_to new_user_session_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_delete_modal.html.haml
.modal.js-post-del-modal
  .modal-back.post-del-back
  .post-del-modal
    .post-del-modal__msg
      この投稿を削除します。本当によろしいですか？
    .post-del-modal__btn
      .post-del-modal__btn__back.post-del-back
        戻る
      .post-del-modal__btn__move
        

app/views/posts/_form.html.haml
.posts-new__form
  = form_with(model: post, data: { remote: false }) do |f|
    .posts-new__form__content
      .sub-title
        記事の種類
      = f.select :post_type, options_for_select(Post.post_types.keys, selected: post.post_type), {}, {class: 'select-box-default'}
    .posts-new__form__content
      .sub-title
        タイトル
      = f.text_field :title, value: post.title, class: "text-field-default", placeholder: "40字以内"
      - post.errors.full_messages_for(:title).each do |err_msg|
        .error-messages
          = err_msg
    .posts-new__form__content
      .sub-title
        内容
      = f.text_area :contents, value: post.contents, class: "text-area-default"
      - post.errors.full_messages_for(:contents).each do |err_msg|
        .error-messages
          = err_msg
    = f.submit "登録する", class: "edit-btn-default posts-new__form__btn"

app/views/posts/_post.html.haml
- if posts.present?
  - posts.each do |post|
    .post-container
      .post-container__top
        .post-container__top__left
          - if post.user.img.present?
            = image_tag(post.user.img.to_s, class: "post-container__top__left__userimg")
          - else
            = image_tag("default_user.png", class: "post-container__top__left__userimg")
          .post-container__top__left__contents__title
            = link_to post.title, post_path(post.id)
            .post-container__top__left__contents__name
              = link_to post.user.nickname, user_path(post.user.id)
        .post-container__top__right
          - if post.post_type == "バンドメンバー募集"
            .post-container__top__right--recruit
              = post.post_type_icon
          - elsif post.post_type == "バンド参加希望"
            .post-container__top__right--entry
              = post.post_type_icon
          - else
            .post-container__top__right--other
              = post.post_type_icon
      .post-container__bottom
        .post-container__bottom__contents
          = post.contents_cut
        .post-container__bottom__date
          投稿日時：
          = post.created_at.strftime("%Y/%m/%d %H:%M")
          %br
          更新日時：
          = post.updated_at.strftime("%Y/%m/%d %H:%M")
- else
  .nothing-default
    該当の記事はありません

app/views/posts/_search.html.haml
.search-box
  .post-search-form
    .sub-title
      投稿検索
    = form_with(url: search_posts_path, local: true, method: :get, data: { remote: false }) do |f|
      .post-search-form__title
        記事の種類
      .post-search-form__keyword
        = f.select :post_type, options_for_select(Post.post_types.keys, selected: params[:post_type]), {}, {class: 'select-box-default'}
      .post-search-form__title
        キーワード
      .post-search-form__keyword
        = f.text_field :keyword, value: params[:keyword]
      = f.submit "検索する", class: "side-search-btn"

app/views/posts/edit.html.haml
.posts-new-page
  .main-container
    .inner-container
      .posts-new
        .posts-new__title.main-title
          投稿内容編集
        .posts-new__form
          = render 'form', { post: @post }

app/views/posts/index.html.haml
.main-container
  .inner-container-wide
    .posts-index
      .posts-index__title
        .posts-index__title__name.main-title
          投稿一覧
        .posts-index__title__operate
          = link_to "新規投稿", new_post_path, class: "oparate-btn-blue"
      .posts-index__posts
        = render partial: "post", locals: { posts: @posts }
    .side-bar
      = render partial: "search"

app/views/posts/new.html.haml
.main-container
  .inner-container
    .posts-new
      .posts-new__title.main-title
        新規投稿 
      .posts-new__form
        = render partial: 'form', locals: { post: @post }

app/views/posts/show.html.haml
.main-container
  .inner-container-wide
    .post-show
      .post-show__title
        .post-show__title__name.main-title
          = @post.title
        .post-show__title__operate
          - if user_signed_in?
            - if @post.user.id == current_user&.id
              = link_to "編集する", edit_post_path(@post.id), class: "oparate-btn-blue"
              = link_to "削除する", post_path(@post.id), method: :delete, class: "oparate-btn-red post-del-btn"
      .post-show__details
        .sub-title
          投稿の種類
        .post-show__details__value
          - if @post.post_type == "バンドメンバー募集"
            .post-type--recruit
              = @post.post_type_icon
          - elsif @post.post_type == "バンド参加希望"
            .post-type--entry
              = @post.post_type_icon
          - else
            .post-type--other
              = @post.post_type_icon
          .post-type__string
            = @post.post_type
        .sub-title
          投稿者
        .post-show__details__value
          = link_to @post.user.nickname, user_path(@post.user)
          - if @post.user.id != current_user&.id
            = link_to room_judge_user_chatrooms_path(@post.user), class: "send-message-btn" do
              投稿者にメッセージを送る
              = icon 'fas', 'angle-right'
        .sub-title
          内容
        .post-show__details__value
          = simple_format(@post.contents)
    .side-bar
      = render partial: "search"
= render partial: "delete_modal"