config/routes.rb
Rails.application.routes.draw do
  
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  root 'top#index'

  resources :studios, only: [:show] do
    resources :reserves, only: [:show, :update] do
      collection do
        get :duplicate
      end
    end
  end

  resources :users, only: [:show, :edit, :update] do
    resources :chatrooms, only: [:index] do
      collection do
        get :room_judge
      end
    end
    
    collection do
      get :reserve
      get :notice
      get :search
    end
  end

  resources :user_reserves, only: [:index, :destroy]

  resources :posts do
    collection do
      get :search
    end
  end

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end

  resources :sessions, as: :music_sessions do
    resources :entry_sessions, only: [:create, :destroy]

    resources :entry_musics, only: [:create, :show, :edit, :update, :destroy] do
      resources :entry_parts, only: [:update] do
        member do
          get 'cancel'
        end
      end
    end

    collection do
      post :confirm
      get  :search
    end
  end
  get '*anything', to: 'errors#routing_error'
end

app/models/entry_music.rb
class EntryMusic < ApplicationRecord

  belongs_to :session
  has_many   :entry_parts, dependent: :destroy
  belongs_to :user

  validates :music_name, presence: true
  validates :artist_name, presence: true

  def edit_youtube_url
    edit_url = nil

    if youtube_url.match("https://www.youtube.com/watch")
      edit_url = youtube_url.gsub("https://www.youtube.com/watch?v=", "https://www.youtube.com/embed/")
      edit_url = edit_url.sub(/&.+/,'')
    elsif youtube_url.match("https://youtu.be")
      edit_url = youtube_url.gsub("https://youtu.be", "https://www.youtube.com/embed")
    end
    self.youtube_url_embed = edit_url
  end
end

app/controllers/entry_musics_controller.rb
class EntryMusicsController < ApplicationController

  before_action :sign_in_check, only: [:create, :edit, :update, :destroy]
  before_action :set_session_entry_music, only: [:show, :edit, :update]

  def show
    @current_user_entry = @session.current_user_entry_judge(current_user)
    @entry_parts = @entry_music.entry_parts
  end

  def create
    begin
      # トランザクション開始
      ActiveRecord::Base.transaction do
        
        @entry_music = EntryMusic.new(entry_music_params)
        @entry_music.edit_youtube_url
        # エントリー曲の保存成功時
        if @entry_music.save!
          # 各パートの登録処理(Vo〜Key)
          entry_part_params_array = entry_part_params.to_h.to_a
          entry_part_params_array.each_with_index do |param, cnt|
            entry_part = EntryPart.new
            entry_part.set_default_part(params[:music_session_id], @entry_music.id, param, cnt)
            entry_part.save!
          end
        end
      end
      redirect_to music_session_path(params[:music_session_id])
    rescue => e
      error_log = ErrorLog.new
      error_log.create_log(params, e, request.remote_ip)
      render template: "common/error1"
    end
  end

  def edit
    @entry_parts = @entry_music.entry_parts
  end

  def update
    begin
      @entry_music.youtube_url = entry_music_params[:youtube_url]
      @entry_music.edit_youtube_url
      @entry_parts = @entry_music.entry_parts
      # エントリー曲の更新
      @entry_music.update!(entry_music_params)
      flash[:notice] = '変更を保存しました'
      redirect_to action: :show
    rescue ActiveRecord::RecordInvalid => e
      render :edit
    rescue => e
      error_log = ErrorLog.new
      error_log.create_log(params, e, request.remote_ip)
      render template: "common/error1"
    end
  end

  def destroy
    EntryMusic.destroy(params[:id])
    redirect_to music_session_path(params[:music_session_id])
  end

  private
  def entry_music_params
    params.require(:entry_music).permit(:music_name, :artist_name, :youtube_url).merge(user_id: current_user.id, session_id: params[:music_session_id])
  end

  def entry_part_params
    params.require(:entry_music)
          .permit(:vo, :cho, :gt1, :gt2, :ba, :dr, :key)
  end

  def sign_in_check
    unless user_signed_in?
      flash[:notice] = 'ログイン後（または会員登録後）を行ってください'
      redirect_to new_user_session_path
    end
  end

  def set_session_entry_music
    @session = Session.find(params[:music_session_id])
    @entry_music = EntryMusic.find(params[:id])
  end
end

app/helpers/entry_musics_helper.rb
module EntryMusicsHelper
end

app/views/entry_musics/edit.html.haml
.main-container
  .inner-container-wide
    .entry_musics-show
      = render partial: "sessions/title", locals: { session: @session, current_user_entry: @current_user_entry }
      = link_to "「#{@session.title}」トップへ戻る", music_session_path(@session)
      .entry_musics-show__sub-title
        .entry_musics-show__sub-title__name.sub-title
          = @entry_music.music_name
        .entry_musics-show__sub-title__operate
          = link_to "編集をやめる", music_session_entry_music_path(@session, @entry_music), class: "oparate-btn-red"
      = form_with(model: [@session, @entry_music], url: music_session_entry_music_path(@session, @entry_music), data: { remote: false }) do |f|
        %table.entry_musics-show__info
          %tr
            %th 曲名
            %td
              = f.text_field :music_name, value: @entry_music.music_name, class: "text-field-short"
              - @entry_music.errors.full_messages_for(:music_name).each do |err_msg|
                .error-messages
                  = err_msg
          %tr
            %th アーティスト名
            %td
              = f.text_field :artist_name, value: @entry_music.artist_name, class: "text-field-short"
              - @entry_music.errors.full_messages_for(:artist_name).each do |err_msg|
                .error-messages
                  = err_msg
          %tr
            %th 必須パート
            %td
              - @entry_parts.each do |entry_part|
                - if entry_part.apply_status == 1
                  = entry_part.part_name
          %tr
            %th 任意パート
            %td
              - @entry_parts.each do |entry_part|
                - if entry_part.apply_status == 2
                  = entry_part.part_name
          %tr
            %th 追加者
            %td
              = @entry_music.user.nickname
          %tr
            %th 追加日時
            %td
              = @entry_music.created_at.strftime("%Y/%m/%d %H:%M")
          %tr
            %th 成立状況
            %td
              = @entry_music.complete_status
          %tr
            %th 参考音源
            %td
              = f.text_field :youtube_url, value: @entry_music.youtube_url, class: "text-field-short", placeholder: "YoutubeのURLを入力"
        = f.submit "変更する", class: "edit-btn-default entry_musics-show__btn"
    .side-bar
      = render partial: "sessions/search"

app/views/entry_musics/show.html.haml
.main-container
  .inner-container-wide
    .entry_musics-show
      = render partial: "sessions/title", locals: { session: @session, current_user_entry: @current_user_entry }
      = link_to "「#{@session.title}」トップへ戻る", music_session_path(@session)
      .entry_musics-show__sub-title
        .entry_musics-show__sub-title__name.sub-title
          = @entry_music.music_name
        .entry_musics-show__sub-title__operate
          = link_to "編集する", edit_music_session_entry_music_path, class: "oparate-btn-blue"
          = link_to "削除する", music_session_entry_music_path, method: :delete, class: "oparate-btn-red"
      %table.entry_musics-show__info
        %tr
          %th 曲名
          %td
            = @entry_music.music_name
        %tr
          %th アーティスト名
          %td
            = @entry_music.artist_name
        %tr
          %th 必須パート
          %td
            - @entry_parts.each do |entry_part|
              - if entry_part.apply_status == 1
                = entry_part.part_name
        %tr
          %th 任意パート
          %td
            - @entry_parts.each do |entry_part|
              - if entry_part.apply_status == 2
                = entry_part.part_name
        %tr
          %th 追加者
          %td
            = @entry_music.user.nickname
        %tr
          %th 追加日時
          %td
            = @entry_music.created_at.strftime("%Y/%m/%d %H:%M")
        %tr
          %th 成立状況
          %td
            = @entry_music.complete_status
        %tr
          %th 参考音源
          %td
            - if @entry_music.youtube_url.present?
              = link_to @entry_music.youtube_url
              %iframe{frameborder: "0", height: "390", src: @entry_music.youtube_url_embed, type: "text/html", width: "640"}
            -else
              ー
    .side-bar
      = render partial: "sessions/search"